package com.apartment.maintenance.constants;

public enum SmsTemplate {

    APP_LOGIN_OTP("FLOW_ID_APP_LOGIN_OTP"),

    PAYMENT_REQUEST_CREATED("FLOW_ID_PAYMENT_REQUEST_CREATED"),
    PAYMENT_DUE_REMINDER("FLOW_ID_PAYMENT_DUE_REMINDER"),
    PAYMENT_SUBMITTED("FLOW_ID_PAYMENT_SUBMITTED"),
    PAYMENT_APPROVED("FLOW_ID_PAYMENT_APPROVED"),
    PAYMENT_REJECTED("FLOW_ID_PAYMENT_REJECTED"),
    DIRECT_PAYMENT_RECORDED("FLOW_ID_DIRECT_PAYMENT_RECORDED"),

    NOTICE_CREATED("FLOW_ID_NOTICE_CREATED"),
    MEETING_CREATED("FLOW_ID_MEETING_CREATED"),

    COMPLAINT_CREATED("FLOW_ID_COMPLAINT_CREATED"),
    COMPLAINT_UPDATED("FLOW_ID_COMPLAINT_UPDATED"),

    TRIAL_STARTED("FLOW_ID_TRIAL_STARTED"),
    TRIAL_EXPIRY_REMINDER("FLOW_ID_TRIAL_EXPIRY_REMINDER"),
    TRIAL_EXPIRED("FLOW_ID_TRIAL_EXPIRED"),

    SUBSCRIPTION_ACTIVATED("FLOW_ID_SUBSCRIPTION_ACTIVATED"),
    SUBSCRIPTION_EXPIRY_REMINDER("FLOW_ID_SUBSCRIPTION_EXPIRY_REMINDER"),
    SUBSCRIPTION_EXPIRED("FLOW_ID_SUBSCRIPTION_EXPIRED");

    private final String flowId;

    SmsTemplate(String flowId) {
        this.flowId = flowId;
    }

    public String getFlowId() {
        return flowId;
    }
}